
version: "3.9"

services:
  # --------------------------
  # PROVIDER SERVICES
  # --------------------------

  provider-identityhub-db:
    image: postgres:15
    container_name: provider-identityhub-db
    restart: always
    env_file:
      - provider/identityhub_db/resources/.env
    ports:
      - "5436:5432"
    volumes:
      - pg_data_provider_identity:/var/lib/postgresql/data
      - ./provider/identityhub_db/resources/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  provider-vault:
    image: hashicorp/vault:1.18.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8400:8200"
    cap_add:
      - IPC_LOCK
    command: ["server", "-dev"]

  provider-connector-db:
    image: postgres:15
    container_name: provider-connector-db
    environment:
      POSTGRES_USER: connector
      POSTGRES_PASSWORD: connector
      POSTGRES_DB: connector
    ports:
      - "5432:5432"

  provider-identityhub:
    image: ghcr.io/ilkkanis/identity-hub:0.12.0
    container_name: provider-identityhub
    env_file: ./provider/identityhub/.env
    volumes:
      - ./provider/identityhub/configuration:/app/configuration
    ports:
      - "7090:7090"
      - "7091:7091"
      - "7092:7092"
      - "7093:7093"
      - "7095:7095"
    depends_on:
     provider-identityhub-db:
      condition: service_healthy

  provider-controlplane:
    image: ghcr.io/ilkkanis/controlplane:0.12.0
    container_name: provider-controlplane
    env_file: ./provider/controlplane/.env
    depends_on:
      - provider-connector-db
      - provider-vault
      - provider-identityhub
    volumes:
      - ./participants.local.json:/app/configuration/participants.local.json
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"

  provider-dataplane:
    image: ghcr.io/ilkkanis/dataplane:0.12.0
    container_name: provider-dataplane
    env_file: ./provider/dataplane/.env
    depends_on:
      - provider-controlplane
    ports:
      - "8180:8180"

  # --------------------------
  # CONSUMER SERVICES
  # --------------------------

  consumer-vault:
    image: hashicorp/vault:1.18.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8300:8200"
    cap_add:
      - IPC_LOCK
    command: ["server", "-dev"]

  consumer-connector-db:
    image: postgres:15
    container_name: consumer-connector-db
    environment:
      POSTGRES_USER: connector
      POSTGRES_PASSWORD: connector
      POSTGRES_DB: connector
    ports:
      - "5433:5432"

  consumer-identityhub:
    image: ghcr.io/ilkkanis/identity-hub:0.12.0
    container_name: consumer-identityhub
    env_file: ./consumer/identityhub/.env
    volumes:
      - ./consumer/identityhub/configuration:/app/configuration
    ports:
      - "8090:7090"
      - "8091:7091"
      - "8092:7092"
      - "8093:7093"
      - "8095:7095"

  consumer-controlplane:
    image: ghcr.io/ilkkanis/controlplane:0.12.0
    container_name: consumer-controlplane
    env_file: ./consumer/controlplane/.env
    depends_on:
      - consumer-connector-db
      - consumer-vault
      - consumer-identityhub
    volumes:
      - ./participants.local.json:/app/configuration/participants.local.json
    ports:
      - "9080:9080"
      - "9081:9081"
      - "9082:9082"
      - "9083:9083"
      - "9084:9084"
      - "9085:9085"

  consumer-dataplane:
    image: ghcr.io/ilkkanis/dataplane:0.12.0
    container_name: consumer-dataplane
    env_file: ./consumer/dataplane/.env
    depends_on:
      - consumer-controlplane
    ports:
      - "9180:9180"

# --------------------------
# NAMED VOLUMES
# --------------------------
volumes:
  pg_data_provider_identity:
